CREATE TABLE ft_operations (
  id bigint(14) unsigned auto_increment,
  project_id bigint(14) unsigned,
  engineer_id mediumint(10) unsigned,
  term_begin_exp date,
  term_end_exp date,
  term_memo varchar(256),
  base decimal(10,0) default 0,
  excess decimal(10,0) default 0,
  deduction decimal(10,0) default 0,
  demand_exc_tax decimal(10,0) default 0,
  demand_inc_tax decimal(10,0) default 0,
  payment_exc_tax decimal(10,0) default 0,
  payment_inc_tax decimal(10,0) default 0,
  welfare_fee decimal(10,0) default 0,
  transportation_fee decimal(10,0) default 0,
  gross_profit decimal(10,0) default 0,
  gross_profit_rate decimal(2,2) default 0,
  tax decimal(10,0) default 0,
  settlement_from mediumint(10) unsigned,
  settlement_to mediumint(10) unsigned,
  contract_date date,
  demand_memo varchar(256),
  payment_memo varchar(256),
  demand_site varchar(64),
  payment_site varchar(64),
  cutoff_date date,
  other_memo varchar(256),
  is_active tinyint(1) unsigned default 1,
  is_fixed tinyint(1) unsigned default 0,
  creator_id mediumint(10) unsigned,
  modifier_id mediumint(10) unsigned,
  dt_created timestamp default CURRENT_TIMESTAMP,
  dt_modified timestamp default CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
